name: "Docker Image CI"

env:
  HUGO_VERSION: "0.55.5"
  CONTAINER_IMAGE_NAME: "nrcga"
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_REGISTRY: docker.pkg.github.com

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Registry
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN $DOCKER_REGISTRY

      - name: Building Docker Image
        run:
          # Change all uppercase to lowercase
          REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')

          docker build --build-arg HUGO_VERSION=$HUGO_VERSION --no-cache -t $DOCKER_REGISTRY/$REPOSITORY/nrcga:$HUGO_VERSION-$GITHUB_RUN_ID -t $DOCKER_REGISTRY/$REPOSITORY/nrcga:latest .

      - name: Push Docker Container to Registry
        run:
          # Change all uppercase to lowercase
          GITHUB_REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')

          docker push $DOCKER_REGISTRY/$GITHUB_REPOSITORY/nrcga
